### ISSUE TITLE
not load HMI screen

### ISSUE THREAD

**Issue by runtimevic** [benhar-dev/tchmi-multi-screen#2]
Hello Ben,
not load HMI screen, error:

It has stopped working for me, I think it is when using the new project creation template wizard.
I don't know how to fix it? I am very interested in solving it since I have to send a different screen to different TVs.
thanks you.

**Comment by runtimevic** [comment]
the error was that I had made screen as content and the screen has to be view

**Comment by benhar-dev** [comment]
Hi @runtimevic, based on your email, am I correct to understand that this is now working.  The problem was that your view was located inside a folder?

**Comment by runtimevic** [comment]
> Hi @runtimevic, based on your email, am I correct to understand that this is now working. The problem was that your view was located inside a folder?

If so, I'll close the issue.
